Description: BLEA ECS App sample for guest accounts (uksb-1tupboc58) (tag:blea-guest-ecs-app-sample-frontend)
Resources:
  FrontendWebAclFA218467:
    Type: AWS::WAFv2::WebACL
    Properties:
      DefaultAction:
        Allow: {}
      Name: DevBLEAEcsAppFrontend07EAA01E
      Rules:
        - Name: AWSManagedRulesCommonRuleSet
          OverrideAction:
            Count: {}
          Priority: 1
          Statement:
            ManagedRuleGroupStatement:
              Name: AWSManagedRulesCommonRuleSet
              VendorName: AWS
          VisibilityConfig:
            CloudWatchMetricsEnabled: true
            MetricName: AWS-AWSManagedRulesCommonRuleSet
            SampledRequestsEnabled: true
        - Name: AWSManagedRulesKnownBadInputsRuleSet
          OverrideAction:
            Count: {}
          Priority: 2
          Statement:
            ManagedRuleGroupStatement:
              Name: AWSManagedRulesKnownBadInputsRuleSet
              VendorName: AWS
          VisibilityConfig:
            CloudWatchMetricsEnabled: true
            MetricName: AWS-AWSManagedRulesKnownBadInputsRuleSet
            SampledRequestsEnabled: true
        - Name: AWSManagedRulesAmazonIpReputationList
          OverrideAction:
            Count: {}
          Priority: 3
          Statement:
            ManagedRuleGroupStatement:
              Name: AWSManagedRulesAmazonIpReputationList
              VendorName: AWS
          VisibilityConfig:
            CloudWatchMetricsEnabled: true
            MetricName: AWS-AWSManagedRulesAmazonIpReputationList
            SampledRequestsEnabled: true
        - Name: AWSManagedRulesLinuxRuleSet
          OverrideAction:
            Count: {}
          Priority: 4
          Statement:
            ManagedRuleGroupStatement:
              Name: AWSManagedRulesLinuxRuleSet
              VendorName: AWS
          VisibilityConfig:
            CloudWatchMetricsEnabled: true
            MetricName: AWS-AWSManagedRulesLinuxRuleSet
            SampledRequestsEnabled: true
        - Name: AWSManagedRulesSQLiRuleSet
          OverrideAction:
            Count: {}
          Priority: 5
          Statement:
            ManagedRuleGroupStatement:
              Name: AWSManagedRulesSQLiRuleSet
              VendorName: AWS
          VisibilityConfig:
            CloudWatchMetricsEnabled: true
            MetricName: AWS-AWSManagedRulesSQLiRuleSet
            SampledRequestsEnabled: true
      Scope: CLOUDFRONT
      VisibilityConfig:
        CloudWatchMetricsEnabled: true
        MetricName: DevBLEAEcsAppFrontend07EAA01E
        SampledRequestsEnabled: true
    Metadata:
      aws:cdk:path: Dev-BLEAEcsAppFrontend/Frontend/WebAcl
  FrontendWebContentBucketCD12DDF8:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Metadata:
      aws:cdk:path: Dev-BLEAEcsAppFrontend/Frontend/WebContentBucket/Resource
  FrontendWebContentBucketPolicyC7AADD3B:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: FrontendWebContentBucketCD12DDF8
      PolicyDocument:
        Statement:
          - Action: s3:*
            Condition:
              Bool:
                aws:SecureTransport: "false"
            Effect: Deny
            Principal:
              AWS: "*"
            Resource:
              - Fn::GetAtt:
                  - FrontendWebContentBucketCD12DDF8
                  - Arn
              - Fn::Join:
                  - ""
                  - - Fn::GetAtt:
                        - FrontendWebContentBucketCD12DDF8
                        - Arn
                    - /*
          - Action: s3:GetObject
            Effect: Allow
            Principal:
              CanonicalUser:
                Fn::GetAtt:
                  - FrontendDistributionOrigin2S3OriginFE05A78D
                  - S3CanonicalUserId
            Resource:
              Fn::Join:
                - ""
                - - Fn::GetAtt:
                      - FrontendWebContentBucketCD12DDF8
                      - Arn
                  - /*
        Version: "2012-10-17"
    Metadata:
      aws:cdk:path: Dev-BLEAEcsAppFrontend/Frontend/WebContentBucket/Policy/Resource
  FrontendCloudFrontLogBucket688801AF:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      OwnershipControls:
        Rules:
          - ObjectOwnership: ObjectWriter
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Metadata:
      aws:cdk:path: Dev-BLEAEcsAppFrontend/Frontend/CloudFrontLogBucket/Resource
  FrontendCloudFrontLogBucketPolicy7FCDBABE:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: FrontendCloudFrontLogBucket688801AF
      PolicyDocument:
        Statement:
          - Action: s3:*
            Condition:
              Bool:
                aws:SecureTransport: "false"
            Effect: Deny
            Principal:
              AWS: "*"
            Resource:
              - Fn::GetAtt:
                  - FrontendCloudFrontLogBucket688801AF
                  - Arn
              - Fn::Join:
                  - ""
                  - - Fn::GetAtt:
                        - FrontendCloudFrontLogBucket688801AF
                        - Arn
                    - /*
        Version: "2012-10-17"
    Metadata:
      aws:cdk:path: Dev-BLEAEcsAppFrontend/Frontend/CloudFrontLogBucket/Policy/Resource
  FrontendDistributionOrigin2S3OriginFE05A78D:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: Identity for DevBLEAEcsAppFrontendDistributionOrigin2FA686FE7
    Metadata:
      aws:cdk:path: Dev-BLEAEcsAppFrontend/Frontend/Distribution/Origin2/S3Origin/Resource
  FrontendDistributionC0C89627:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        CacheBehaviors:
          - CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
            Compress: true
            PathPattern: /static/*
            TargetOriginId: DevBLEAEcsAppFrontendDistributionOrigin2FA686FE7
            ViewerProtocolPolicy: redirect-to-https
        CustomErrorResponses:
          - ErrorCachingMinTTL: 20
            ErrorCode: 403
            ResponseCode: 403
            ResponsePagePath: /static/sorry.html
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
            - PUT
            - PATCH
            - POST
            - DELETE
          CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad
          Compress: true
          OriginRequestPolicyId: 216adef6-5c7f-47e4-b989-5492eafa07d3
          TargetOriginId: DevBLEAEcsAppFrontendDistributionOrigin1B126A7CF
          ViewerProtocolPolicy: https-only
        DefaultRootObject: /
        Enabled: true
        HttpVersion: http2
        IPV6Enabled: true
        Logging:
          Bucket:
            Fn::GetAtt:
              - FrontendCloudFrontLogBucket688801AF
              - RegionalDomainName
          IncludeCookies: true
          Prefix: CloudFrontAccessLogs/
        Origins:
          - CustomOriginConfig:
              OriginProtocolPolicy: http-only
              OriginSSLProtocols:
                - TLSv1.2
            DomainName:
              Fn::GetAtt:
                - ExportsReader8B249524
                - /cdk/exports/Dev-BLEAEcsAppFrontend/DevBLEAEcsAppuseast2FnGetAttEcsAppAlb74CC21B3DNSName048839DD
            Id: DevBLEAEcsAppFrontendDistributionOrigin1B126A7CF
          - DomainName:
              Fn::GetAtt:
                - FrontendWebContentBucketCD12DDF8
                - RegionalDomainName
            Id: DevBLEAEcsAppFrontendDistributionOrigin2FA686FE7
            S3OriginConfig:
              OriginAccessIdentity:
                Fn::Join:
                  - ""
                  - - origin-access-identity/cloudfront/
                    - Ref: FrontendDistributionOrigin2S3OriginFE05A78D
        WebACLId:
          Fn::GetAtt:
            - FrontendWebAclFA218467
            - Arn
    Metadata:
      aws:cdk:path: Dev-BLEAEcsAppFrontend/Frontend/Distribution/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/3WOQQuCQBCFf0v3dVIjoqMZQRAYdugYuq4xaruxM6uE+N9DDerS6b15vG94IQTrLQSLrCNPFrXXYA79hTNZi6yjW99lZRtCXOqryqP4JGgF/c7JWrGIS/1xs5xNg/L1jed7ELIxriit0Qz9Hokt5o7RaJFYvKOOpFREx0JpRp7weAQOI/Cv8ftmGMYkcfx006ZUkXFWqkFoUyioaNmGPgQb8BcVIXrWacaHgnTWN2jl8r4BAQAA
    Metadata:
      aws:cdk:path: Dev-BLEAEcsAppFrontend/CDKMetadata/Default
  ExportsReader8B249524:
    Type: Custom::CrossRegionExportReader
    Properties:
      ServiceToken:
        Fn::GetAtt:
          - CustomCrossRegionExportReaderCustomResourceProviderHandler46647B68
          - Arn
      ReaderProps:
        region: us-east-1
        prefix: Dev-BLEAEcsAppFrontend
        imports:
          /cdk/exports/Dev-BLEAEcsAppFrontend/DevBLEAEcsAppuseast2FnGetAttEcsAppAlb74CC21B3DNSName048839DD: "{{resolve:ssm:/cdk/exports/Dev-BLEAEcsAppFrontend/DevBLEAEcsAppuseast2FnGetAttEcsAppAlb74CC21B3DNSName048839DD}}"
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: Dev-BLEAEcsAppFrontend/ExportsReader/Resource/Default
  CustomCrossRegionExportReaderCustomResourceProviderRole10531BBD:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
      ManagedPolicyArns:
        - Fn::Sub: arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: Inline
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Resource:
                  Fn::Join:
                    - ""
                    - - "arn:"
                      - Ref: AWS::Partition
                      - :ssm:us-east-1:818740031270:parameter/cdk/exports/Dev-BLEAEcsAppFrontend/*
                Action:
                  - ssm:AddTagsToResource
                  - ssm:RemoveTagsFromResource
                  - ssm:GetParameters
    Metadata:
      aws:cdk:path: Dev-BLEAEcsAppFrontend/Custom::CrossRegionExportReaderCustomResourceProvider/Role
  CustomCrossRegionExportReaderCustomResourceProviderHandler46647B68:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: cdk-hnb659fds-assets-818740031270-us-east-1
        S3Key: 8acca95a9957d02a9f3ec124c9869c5d5b70a7fb3e332120850781ecc9363037.zip
      Timeout: 900
      MemorySize: 128
      Handler: __entrypoint__.handler
      Role:
        Fn::GetAtt:
          - CustomCrossRegionExportReaderCustomResourceProviderRole10531BBD
          - Arn
      Runtime: nodejs20.x
    DependsOn:
      - CustomCrossRegionExportReaderCustomResourceProviderRole10531BBD
    Metadata:
      aws:cdk:path: Dev-BLEAEcsAppFrontend/Custom::CrossRegionExportReaderCustomResourceProvider/Handler
      aws:asset:path: asset.8acca95a9957d02a9f3ec124c9869c5d5b70a7fb3e332120850781ecc9363037
      aws:asset:property: Code
  ExportsWriteruseast2828FA26B86FBEFA7:
    Type: Custom::CrossRegionExportWriter
    Properties:
      ServiceToken:
        Fn::GetAtt:
          - CustomCrossRegionExportWriterCustomResourceProviderHandlerD8786E8A
          - Arn
      WriterProps:
        region: us-east-2
        exports:
          /cdk/exports/Dev-BLEAEcsAppMonitoring/DevBLEAEcsAppFrontenduseast1FnGetAttFrontendDistributionC0C89627DomainName34318E09:
            Fn::GetAtt:
              - FrontendDistributionC0C89627
              - DomainName
          /cdk/exports/Dev-BLEAEcsAppMonitoring/DevBLEAEcsAppFrontenduseast1RefFrontendDistributionC0C89627E26C774F:
            Ref: FrontendDistributionC0C89627
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: Dev-BLEAEcsAppFrontend/ExportsWriteruseast2828FA26B/Resource/Default
  CustomCrossRegionExportWriterCustomResourceProviderRoleC951B1E1:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
      ManagedPolicyArns:
        - Fn::Sub: arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: Inline
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Resource:
                  - Fn::Join:
                      - ""
                      - - "arn:"
                        - Ref: AWS::Partition
                        - :ssm:us-east-2:818740031270:parameter/cdk/exports/*
                Action:
                  - ssm:DeleteParameters
                  - ssm:ListTagsForResource
                  - ssm:GetParameters
                  - ssm:PutParameter
    Metadata:
      aws:cdk:path: Dev-BLEAEcsAppFrontend/Custom::CrossRegionExportWriterCustomResourceProvider/Role
  CustomCrossRegionExportWriterCustomResourceProviderHandlerD8786E8A:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: cdk-hnb659fds-assets-818740031270-us-east-1
        S3Key: 246cb27aa0cb552c81fdca061092d0905aa4d2529e8b52b5598c069f18be51d7.zip
      Timeout: 900
      MemorySize: 128
      Handler: __entrypoint__.handler
      Role:
        Fn::GetAtt:
          - CustomCrossRegionExportWriterCustomResourceProviderRoleC951B1E1
          - Arn
      Runtime: nodejs20.x
    DependsOn:
      - CustomCrossRegionExportWriterCustomResourceProviderRoleC951B1E1
    Metadata:
      aws:cdk:path: Dev-BLEAEcsAppFrontend/Custom::CrossRegionExportWriterCustomResourceProvider/Handler
      aws:asset:path: asset.246cb27aa0cb552c81fdca061092d0905aa4d2529e8b52b5598c069f18be51d7
      aws:asset:property: Code
Outputs:
  ExportsOutputFnGetAttFrontendDistributionC0C89627DomainName78150ED0:
    Value:
      Fn::GetAtt:
        - FrontendDistributionC0C89627
        - DomainName
    Export:
      Name: Dev-BLEAEcsAppFrontend:ExportsOutputFnGetAttFrontendDistributionC0C89627DomainName78150ED0
Parameters:
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]

